# Generated by Django 3.2.7 on 2021-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210910_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(default='okay', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default='okay', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(default='okay', max_length=8),
            preserve_default=False,
        ),
    ]
