# Generated by Django 3.2.7 on 2022-02-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210915_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
    ]
