# Generated by Django 3.2.7 on 2021-09-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='okay_react', max_length=10, null=True)),
                ('place', models.CharField(default='okay_react', max_length=10, null=True)),
                ('image', models.ImageField(upload_to='test_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='main_app.county')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='poultry')),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='poultry_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='poultry_images/')),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('price', models.CharField(default='Negotiable', max_length=25)),
                ('date_posted', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poultries', to='main_app.category')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poultries', to='main_app.county')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poultries', to='main_app.subcounty')),
            ],
            options={
                'ordering': ('-date_posted', '-id'),
            },
        ),
    ]
