# Generated by Django 3.2.7 on 2021-09-02 09:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
