# Generated by Django 3.2.5 on 2021-07-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='poultry',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'ordering': ['name']},
        ),
    ]
