# Generated by Django 3.2.5 on 2021-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_poultry_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='poultry',
            name='slug',
            field=models.SlugField(default='poultry'),
        ),
    ]
