# Generated by Django 3.2.7 on 2021-09-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_poultry_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
        migrations.RemoveField(
            model_name='poultry',
            name='thumbnail',
        ),
    ]
