# Generated by Django 3.2.5 on 2021-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='okay', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='place',
            field=models.CharField(default='okay', max_length=10, null=True),
        ),
    ]
