# Generated by Django 3.2.5 on 2021-07-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210726_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='main_app.county'),
            preserve_default=False,
        ),
    ]
