# Generated by Django 3.2.5 on 2021-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210806_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(default='null', upload_to='test_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='okay_react', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='place',
            field=models.CharField(default='okay_react', max_length=10, null=True),
        ),
    ]
