# Generated by Django 3.2.5 on 2021-07-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_subcounty_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='poultry',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'ordering': ('name',)},
        ),
    ]
