# Generated by Django 3.2.5 on 2021-07-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210728_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poultry',
            old_name='name',
            new_name='title',
        ),
    ]
