# Generated by Django 3.2.5 on 2021-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210806_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='test_images/'),
        ),
    ]
