# Generated by Django 3.2.7 on 2021-11-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211028_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poultry',
            name='approved',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='sponsored',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
