# Generated by Django 3.2.5 on 2021-08-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_testmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(upload_to='test_images/'),
        ),
    ]
