# Generated by Django 3.2.5 on 2021-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_poultry_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultry',
            name='location',
            field=models.CharField(default='Ikutha town opposite level 4 hospital, shop 4', max_length=100),
            preserve_default=False,
        ),
    ]
