# Generated by Django 3.2.5 on 2021-07-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_poultry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultry',
            name='contact',
            field=models.CharField(default='0711113333', max_length=15),
            preserve_default=False,
        ),
    ]
